"""Type stubs for the C++ chess engine extension (pybind11)."""

from __future__ import annotations

from collections.abc import Sequence

# ── Enums ────────────────────────────────────────────────────────────

class Color:
    WHITE: Color
    BLACK: Color
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __bool__(self) -> bool: ...

class PieceType(int):
    PAWN: PieceType
    KNIGHT: PieceType
    BISHOP: PieceType
    ROOK: PieceType
    QUEEN: PieceType
    KING: PieceType
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class GameState:
    ONGOING: GameState
    CHECKMATE: GameState
    STALEMATE: GameState
    DRAW_BY_FIFTY_MOVE: GameState
    DRAW_BY_INSUFFICIENT_MATERIAL: GameState
    DRAW_BY_REPETITION: GameState
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# ── Enum-level constants ─────────────────────────────────────────────

WHITE: Color
BLACK: Color
PAWN: PieceType
KNIGHT: PieceType
BISHOP: PieceType
ROOK: PieceType
QUEEN: PieceType
KING: PieceType
ONGOING: GameState
CHECKMATE: GameState
STALEMATE: GameState
DRAW_BY_FIFTY_MOVE: GameState
DRAW_BY_INSUFFICIENT_MATERIAL: GameState
DRAW_BY_REPETITION: GameState

SQUARES: list[int]

# ── Types ────────────────────────────────────────────────────────────

class Piece:
    @property
    def color(self) -> Color: ...
    @property
    def piece_type(self) -> PieceType: ...
    @property
    def type(self) -> PieceType: ...
    def symbol(self) -> str: ...

class Move:
    from_square: int
    to_square: int
    promotion: int
    def uci(self) -> str: ...
    @staticmethod
    def from_uci(uci: str) -> Move: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Board:
    def __init__(self, fen: str = ...) -> None: ...
    @property
    def turn(self) -> bool: ...
    @property
    def legal_moves(self) -> list[Move]: ...
    def fen(self) -> str: ...
    def to_fen(self) -> str: ...
    def set_fen(self, fen: str) -> None: ...
    @staticmethod
    def from_fen(fen: str) -> Board: ...
    def copy(self) -> Board: ...
    def push(self, move: Move) -> None: ...
    def push_san(self, san: str) -> None: ...
    def push_null(self) -> None: ...
    def pop(self) -> Move: ...
    def make_move(self, move: Move) -> None: ...
    def generate_legal_moves(self) -> list[Move]: ...
    def is_game_over(self) -> GameState: ...
    def is_check(self) -> bool: ...
    def is_capture(self, move: Move) -> bool: ...
    def is_castling(self, move: Move) -> bool: ...
    def is_en_passant(self, move: Move) -> bool: ...
    def is_kingside_castling(self, move: Move) -> bool: ...
    def is_queenside_castling(self, move: Move) -> bool: ...
    def piece_at(self, square: int) -> Piece | None: ...
    def pieces(self, piece_type: PieceType, color: Color) -> list[int]: ...
    def king(self, color: Color) -> int: ...
    def get_side_to_move(self) -> bool: ...
    def get_en_passant_square(self) -> int: ...
    def get_halfmove_clock(self) -> int: ...
    def get_fullmove_number(self) -> int: ...
    def get_castling_rights(self) -> int: ...
    def has_kingside_castling_rights(self, color: Color) -> bool: ...
    def has_queenside_castling_rights(self, color: Color) -> bool: ...
    def get_piece_bb(self, piece_type: PieceType, color: Color) -> int: ...
    def get_color_bb(self, color: Color) -> int: ...
    def get_all_pieces_bb(self) -> int: ...
    def perft(self, depth: int) -> int: ...
    def pretty(self) -> str: ...

class Zobrist:
    def __init__(self) -> None: ...
    def hash_board(self, board: Board) -> int: ...
    def make_move_hash(self, board: Board, move: Move) -> int: ...
    def make_null_move_hash(self, board: Board) -> int: ...
    def get_current_hash(self) -> int: ...
    def set_current_hash(self, hash_val: int) -> None: ...
    def invalidate_hash(self) -> None: ...

class StaticExchangeEvaluator:
    def __init__(self) -> None: ...
    def evaluate(self, board: Board, move: Move) -> int: ...

class TTEntry:
    key: int
    depth: int
    score: float
    age: int
    best_move: Move | None
    bound: str

class TranspositionTable:
    max_entries: int
    @property
    def current_age(self) -> int: ...
    def __init__(self, config: object) -> None: ...
    def increment_age(self) -> None: ...
    def clear(self) -> None: ...
    def size(self) -> int: ...
    def probe(self, key: int) -> TTEntry | None: ...
    def try_get_score(
        self, entry: TTEntry, depth: int, alpha: float, beta: float
    ) -> float | None: ...
    def store(
        self,
        key: int,
        depth: int,
        score: float,
        best_move: Move | None,
        bound: str,
    ) -> None: ...

class MoveSorter:
    PIECE_VALUES_CP: dict[int, int]
    @property
    def killer_moves(self) -> dict[int, list[Move]]: ...
    @property
    def history_table(self) -> dict[tuple[int, int, int], int]: ...
    @property
    def countermove_table(self) -> dict[tuple[int, int, int], Move]: ...
    def __init__(self, config: object) -> None: ...
    def reset(self, clear_history: bool = ..., clear_killers: bool = ...) -> None: ...
    def sort_moves(
        self,
        board: Board,
        moves: list[Move],
        ply: int,
        hash_move: Move | None,
        previous_move: Move | None,
    ) -> list[Move]: ...
    def sort_tactical(self, board: Board, moves: list[Move]) -> list[Move]: ...
    def see(self, board: Board, move: Move) -> int: ...
    def on_beta_cutoff(
        self,
        move: Move,
        ply: int,
        depth: int,
        previous_move: Move | None,
        is_tactical: bool,
    ) -> None: ...
    def history_saturation(self) -> float: ...

class SearchStats:
    nodes: int
    qsearch_nodes: int
    depth: int
    seldepth: int
    score: int
    best_move: Move | None
    tt_hits: int
    hashfull: int
    beta_cutoffs: int
    first_move_cuts: int
    killer_cuts: int
    history_cuts: int
    null_move_cuts: int
    pvs_researches: int
    root_move_changes: int

class Search:
    def __init__(self, board: Board) -> None: ...
    def search(self, depth: int) -> int: ...
    def get_stats(self) -> SearchStats: ...
    def reset_stats(self) -> None: ...

class MinimaxStats:
    nodes: int
    depth: int
    seldepth: int
    tt_hits: int
    hashfull: int
    beta_cutoffs: int
    first_move_cuts: int
    killer_cuts: int
    history_cuts: int
    qsearch_nodes: int
    null_move_cuts: int
    pvs_researches: int
    lmr_researches: int
    qs_see_pruning: int
    qs_delta_pruning: int
    check_extensions: int
    iid_searches: int
    root_move_changes: int
    history_saturation: float
    score: int
    def __init__(self) -> None: ...
    def reset(self) -> None: ...

class CppMinimax:
    time_up: bool
    @property
    def stats(self) -> MinimaxStats: ...
    @property
    def node_count(self) -> int: ...
    @property
    def root_best_move(self) -> Move | None: ...
    @property
    def effective_features(self) -> dict[str, bool]: ...
    @property
    def effective_config(self) -> dict[str, object]: ...
    @property
    def feature_stats(self) -> dict[str, dict[str, int]]: ...
    def __init__(
        self,
        board: Board,
        evaluator: object,
        tt: TranspositionTable | None,
        sorter: MoveSorter | None,
        see: StaticExchangeEvaluator | None,
        zobrist: Zobrist | None,
        config: object,
    ) -> None: ...
    def find_best_move(
        self, depth: int, max_time: float | None = ...
    ) -> tuple[float | None, Move | None]: ...
    def reset_state(
        self,
        clear_tt: bool = ...,
        clear_history: bool = ...,
        clear_killers: bool = ...,
    ) -> None: ...
    def check_time_limit(self) -> bool: ...
    def reset_clock(self) -> None: ...

# ── Evaluators submodule ─────────────────────────────────────────────

class _EvaluatorsModule:
    class IEvaluator:
        def __init__(self) -> None: ...
        def go(self, board: Board) -> float: ...

    class MaterialComponent(IEvaluator):
        def __init__(self) -> None: ...
        def score(self, board: Board, phase: float) -> float: ...

    class PSTComponent(IEvaluator):
        def __init__(self, gsc: bool = ...) -> None: ...
        def score(self, board: Board, phase: float) -> float: ...

    class PawnStructureComponent(IEvaluator):
        def __init__(self, gsc: bool = ...) -> None: ...
        def score(self, board: Board, phase: float) -> float: ...

    class MobilityComponent(IEvaluator):
        def __init__(self, gsc: bool = ...) -> None: ...
        def score(self, board: Board, phase: float) -> float: ...

    class KingSafetyComponent(IEvaluator):
        def __init__(self, gsc: bool = ...) -> None: ...
        def score(self, board: Board, phase: float) -> float: ...

    class CompositeEvaluator(IEvaluator):
        def __init__(self) -> None: ...
        def add_component(self, component: _EvaluatorsModule.IEvaluator) -> None: ...
        def components(self) -> list[_EvaluatorsModule.IEvaluator]: ...

    @staticmethod
    def compute_game_phase(board: Board) -> float: ...

evaluators: _EvaluatorsModule

# ── Free functions ───────────────────────────────────────────────────

def compute_attacked_squares(board: Board, color: Color) -> int: ...
def get_attacked_squares(board: Board, color: Color) -> int: ...
def is_in_check(board: Board, color: Color) -> bool: ...
def move_to_uci(move: Move) -> str: ...
def move_to_string(move: Move, board: Board) -> str: ...
def move_debug_string(move: Move, board: Board) -> str: ...
def moves_to_string(moves: Sequence[Move], board: Board) -> str: ...
def square_file(square: int) -> int: ...
def square_rank(square: int) -> int: ...
